### ISSUE TITLE
When `.ts` is import in Component, it does not work on the client

### ISSUE THREAD

**Issue by AkifumiSato** [AkifumiSato/dexr#2]
https://github.com/denoland/deno/issues/4542

**Comment by AkifumiSato** [comment]
Page component path can not support `./`

**Comment by dioslibre** [comment]
Hey @AkifumiSato. I played with the styled-components example a bit, I created a .ts file with a simple function, imported it in the App component, and it seems to work, hooks work too, everything works perfectly, so thank you.

Was this the problem or was it something else?

I'll be using your library for a project of mine and will report if anything comes up.

**Comment by AkifumiSato** [comment]
@dioslibre This issue has been resolved and I forgot to close it.
Please let me know if you find any problems.
Thank you!
